apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # The value of MYSQL_ROOT_PASSWORD should be base64 encoded
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=  # This is the base64 encoding of the string "password"
